# 1. כתובת מסד הנתונים PostgreSQL והשם שלו (store_db)
spring.datasource.url=jdbc:postgresql://localhost:5432/store_db

# 2. שם המשתמש והסיסמה שהגדרת בהתקנה של PostgreSQL
spring.datasource.username=postgres
spring.datasource.password=admin123

# 3. הדרייבר של PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. JPA / Hibernate - ניהול הטבלאות
# update = ספרינג יבנה ויעדכן את הטבלאות (Product, Category) אוטומטית ב-PostgreSQL!
spring.jpa.hibernate.ddl-auto=update

# 5. הצגת שאילתות ה-SQL ב-Console (למעקב ודיבאג)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
